### ISSUE TITLE
7.1.0 Release Plan

### ISSUE THREAD

**Issue by shweaver-MSFT** [windows-toolkit/Graph-Controls#104]
# 7.1.0 Release Plan

Our initial 7.0.0 release is mostly focused on making the authentication providers available so developers can authenticate easily and make their own calls to the Graph with a pre-configured client. But we know there is so much more we can do on top to enable developers to do more with Microsoft Graph in their applications. 

We plan to quickly follow up with a 7.1.0 release, including AAD support in WindowsProvider, helpers for roaming data between apps using Graph, as well as a variety of templated controls for UWP.

### Authentication

- [ ] :one: WindowsProvider supports organizational accounts from AAD.

### Roaming Data Helpers

Developers can roam app and user settings to Graph:

- [ ] :zero::exclamation: in netstandard apps
- [x] :zero: via OneDrive - #74
- [x] :one: via User extensions - #72 #73

###  Graph Enabled Controls

Developers can use Graph enabled controls to:

  - [ ] :zero: visualize miscellaneous Graph endpoints (GraphPresenter) - #17 #54 #56
  - [ ] :zero::exclamation: authenticate a user with the click of a button (LoginButton)
  - [ ] :zero: visualize a single Graph Person (PersonView) #6 #10
  - [ ] :one::exclamation: search and select people from a tokenized picker experience (PeoplePicker)

**Comment by shweaver-MSFT** [comment]
https://aka.ms/wct/blog/7.1
